name: Android Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK required for the Android project
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30  # API level required for the app
          build-tools: 30.0.3

      # Step 4: Build the Android project using Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Step 5: Run unit tests using Gradle
      - name: Run Unit Tests
        run: ./gradlew test

      # Step 6: Package the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk